version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Aa1234567
      MYSQL_ROOT_HOST: '%'
    ports:
      - "33061:3306"
    volumes:
      - "./MysqlConfiguration/db:/var/lib/mysql"
      - "./MysqlConfiguration/init:/docker-entrypoint-initdb.d/"
  backend:
    container_name: backend
    restart: always
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - mysql
      - nginx
  redis:
    container_name: redis
    build:
      context: ./
      dockerfile: ./RedisConfiguration/Dockerfile
    ports:
        - "63791:6379"
    volumes:
        - "./RedisConfiguration/data:/data"
        - "./RedisConfiguration/redis/redis.conf:/etc/redis/redis.conf"
    restart: always
    command: redis-server /etc/redis/redis.conf
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./NginxConfiguration/conf.d:/etc/nginx/conf.d